### PR TITLE
add jack feature flag & conditional use of libm

### PR DESCRIPTION
**Pull request by amomentunfolding**
hellohello
for my project i am using cpal and do not need the jack stuff so i moved it under a feature flag
i thought perhaps it might be useful for others too

cheers

### CODE REVIEW

**Comment by Jikstra** [comment]
That makes sense, thank you :)

**Comment by Jikstra** [comment]
@amomentunfolding I was thinking of having a list of projects using rust-faust in the readme, if you want i would include your project there :)

**Comment by amomentunfolding** [comment]
cool! :)
At this point I don't have much online about this project except for videos where I use it in performances, planning to make a write-up & video at some point in the coming months.. here is one video of it you could include if you want though :) https://www.youtube.com/watch?v=c9TPb6ca5as - I call it 'evo' it is a minimal DAW for generative live looping. Still using SuperCollider here, im in the process of rewriting it with cpal & faust right now - a daunting task but a fun one!

all the best to you!

**Comment by sletz** [comment]
@amomentunfolding  Nice ! I'm interested to put any Faust powered project here https://faust.grame.fr/community/powered-by-faust/  when you think yours is mature enough.

**Pull request merged**
