### PR TITLE
faust-xml and faust-json

### PR DESCRIPTION
**Pull request by crop2000**
deserialize xml files generated by faust

### CODE REVIEW

**Comment by sletz** [comment]
Would it make sense to have something similar for the JSON file generated by ` faust -json foo.dsp` ?

**Comment by crop2000** [comment]
@sletz Not so interested because the json does not provide the struct variable names. Right?

**Comment by sletz** [comment]
Ah right. A bit of history here: the XML export was done years ago, and we decided to switch to the mode modern JSON format more recently. You can see that because the JSON export contains much more infomation. Then it would make sense to also have struct variable names in the JSON export right ?

**Comment by sletz** [comment]
Done in  https://github.com/grame-cncm/faust/commit/e8403e5f582e5120267c60f1d15c1d645d6a1686

**Comment by crop2000** [comment]
i just realized that faust-json is only compatible with faust master-dev ... but i am not sure if i would like to take care of backwards compatibility.

**Comment by obsoleszenz** [comment]
> i just realized that faust-json is only compatible with faust master-dev ... but i am not sure if i would like to take care of backwards compatibility.

I think rust-faust does not need to be backwards compatible with a certain faust version. In case someone needs it they can pin to 0.2 and also only json would be incomplete.

**Pull request merged**
