### PR TITLE
[wip] Flush denormals to zero on supported cpus

### PR DESCRIPTION
**Pull request by Jikstra**
improve performance in some cases

### CODE REVIEW

**Comment by sletz** [comment]
Where is `enable_flush_denormals_to_zero` actually used ? Is housed be added in the process code, before the call to `compute`.

**Comment by Jikstra** [comment]
> Where is `enable_flush_denormals_to_zero` actually used ? Is housed be added in the process code, before the call to `compute`.

One has to call it manually. We are not really parsing the faust code, we are just embedding it with simple search/replace.

**Comment by sletz** [comment]
But you could add the `enable_flush_denormals_to_zero`call in the architecture file , just before calling `compute`. We routinely do that in audio code with C++.

**Comment by sletz** [comment]
In `update_and_compute` maybe ?

**Pull request merged**
